#!/usr/bin/env python

import catkin_pkg.packages
import sys
import yaml
from string import Template
import urllib2
import argparse

parser = argparse.ArgumentParser(description='Produces rosinstall entries to satisfy pandora packages dependencies')
parser.add_argument('root_of_pkgs', help='The root directory of a package or multiple packages')
args = parser.parse_args()

rosinstall = Template("- git: {local-name: $repo_name, uri: 'git@github.com:pandora-auth-ros-pkg/$repo_name.git', version: hydro-devel}")

pkgs = catkin_pkg.packages.find_packages(args.root_of_pkgs)

depends = set([])

for pkg in pkgs:

  depends = depends.union(map(str, pkgs[pkg].build_depends))
  depends = depends.union(map(str, pkgs[pkg].exec_depends))

response = urllib2.urlopen('https://raw.githubusercontent.com/czalidis/ci-scripts/master/pandoradep/repos.yml')
repos = yaml.safe_load(response.read())

repos_to_fetch = set([])

for dep in depends:
  for repo, packages in repos.items():
    for package in packages:
      if dep == package:
        repos_to_fetch.add(repo)

for repo in repos_to_fetch:
  print rosinstall.substitute(repo_name=repo)
