#!/bin/bash

REPO_DIR=upstream
export REPO_NAME="$(git remote -v | head -n1 | awk '{print $2}' | sed 's/.*\///' | sed 's/\.git//')"

mkdir $REPO_DIR
find . -maxdepth 1 -mindepth 1 -not -name ci-scripts -not -name $REPO_DIR -exec mv '{}' $REPO_DIR \;

$JENKINS_SCRIPTS/vagrant_build/vagrant_build.py $WORKSPACE $REPO_DIR $*
